fun foo() {
    try {
    } catch (e: Exception) {
    }
}

// 1 LINENUMBER 3